version: '3'

services:
  spark:
    build: .
    environment:
      - SPARK_MODE=master
    ports:
      - 8005:8080
      - 4040:4040
    volumes:
      - ./data:/data
      - ./src:/src
  spark-worker:
    build: .
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_EXECUTOR_MEMORY=4G
      - SPARK_WORKER_CORES=4
    volumes:
      - ./data:/data
      - ./src:/src
    command: 
      - /bin/bash 
      - -x
      - -o 
      - pipefail 
      - -c 
      - |
        /opt/bitnami/scripts/spark/run.sh &
        sleep 10s
        env | cat >> /home/spark_user/docker_env.txt
        echo Spark123@ | sudo -S service ssh start
        wait
networks:
  default:
    name: airflow_9680b5_airflow
    external: true